- name: Add floating IP to "{{ instance_name }}"
  os_floating_ip:
    cloud: ospcloud
    state: present
    reuse: yes
    server: "{{ instance_name }}"
    network: ext_network
    wait: true
    timeout: 180
  register: instancefloatingip